// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cglbm_cpp_all_cell_loglik_raw
NumericVector cglbm_cpp_all_cell_loglik_raw(const NumericMatrix& value, const IntegerMatrix& status, const NumericMatrix& lower, const NumericMatrix& upper, const NumericMatrix& block_mean, const NumericMatrix& block_variance, Function log_interval_fallback);
RcppExport SEXP _CGLBM_cglbm_cpp_all_cell_loglik_raw(SEXP valueSEXP, SEXP statusSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP block_meanSEXP, SEXP block_varianceSEXP, SEXP log_interval_fallbackSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type value(valueSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type status(statusSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type block_mean(block_meanSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type block_variance(block_varianceSEXP);
    Rcpp::traits::input_parameter< Function >::type log_interval_fallback(log_interval_fallbackSEXP);
    rcpp_result_gen = Rcpp::wrap(cglbm_cpp_all_cell_loglik_raw(value, status, lower, upper, block_mean, block_variance, log_interval_fallback));
    return rcpp_result_gen;
END_RCPP
}
// cglbm_cpp_row_membership_scores_raw
NumericMatrix cglbm_cpp_row_membership_scores_raw(const NumericMatrix& omega, const NumericVector& pi, const NumericVector& log_likelihood);
RcppExport SEXP _CGLBM_cglbm_cpp_row_membership_scores_raw(SEXP omegaSEXP, SEXP piSEXP, SEXP log_likelihoodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type pi(piSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type log_likelihood(log_likelihoodSEXP);
    rcpp_result_gen = Rcpp::wrap(cglbm_cpp_row_membership_scores_raw(omega, pi, log_likelihood));
    return rcpp_result_gen;
END_RCPP
}
// cglbm_cpp_col_membership_scores_raw
NumericMatrix cglbm_cpp_col_membership_scores_raw(const NumericMatrix& tau, const NumericVector& rho, const NumericVector& log_likelihood);
RcppExport SEXP _CGLBM_cglbm_cpp_col_membership_scores_raw(SEXP tauSEXP, SEXP rhoSEXP, SEXP log_likelihoodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type log_likelihood(log_likelihoodSEXP);
    rcpp_result_gen = Rcpp::wrap(cglbm_cpp_col_membership_scores_raw(tau, rho, log_likelihood));
    return rcpp_result_gen;
END_RCPP
}
// cglbm_cpp_membership_objective_raw
double cglbm_cpp_membership_objective_raw(const NumericMatrix& tau, const NumericMatrix& omega, const NumericVector& pi, const NumericVector& rho, const NumericVector& log_likelihood);
RcppExport SEXP _CGLBM_cglbm_cpp_membership_objective_raw(SEXP tauSEXP, SEXP omegaSEXP, SEXP piSEXP, SEXP rhoSEXP, SEXP log_likelihoodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type pi(piSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type log_likelihood(log_likelihoodSEXP);
    rcpp_result_gen = Rcpp::wrap(cglbm_cpp_membership_objective_raw(tau, omega, pi, rho, log_likelihood));
    return rcpp_result_gen;
END_RCPP
}
// cglbm_cpp_weighted_gaussian_em_step_raw
List cglbm_cpp_weighted_gaussian_em_step_raw(const NumericMatrix& value, const IntegerMatrix& status, const NumericMatrix& lower, const NumericMatrix& upper, const NumericMatrix& tau, const NumericMatrix& omega, const NumericMatrix& old_mean, const NumericMatrix& old_variance, const IntegerMatrix& variance_group, const double sigma2_min, const double effective_weight_min, const CharacterVector& cached_complete_censoring_reason, Function numerical_moment_fallback, Function log_interval_fallback);
RcppExport SEXP _CGLBM_cglbm_cpp_weighted_gaussian_em_step_raw(SEXP valueSEXP, SEXP statusSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP tauSEXP, SEXP omegaSEXP, SEXP old_meanSEXP, SEXP old_varianceSEXP, SEXP variance_groupSEXP, SEXP sigma2_minSEXP, SEXP effective_weight_minSEXP, SEXP cached_complete_censoring_reasonSEXP, SEXP numerical_moment_fallbackSEXP, SEXP log_interval_fallbackSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type value(valueSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type status(statusSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type old_mean(old_meanSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type old_variance(old_varianceSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type variance_group(variance_groupSEXP);
    Rcpp::traits::input_parameter< const double >::type sigma2_min(sigma2_minSEXP);
    Rcpp::traits::input_parameter< const double >::type effective_weight_min(effective_weight_minSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type cached_complete_censoring_reason(cached_complete_censoring_reasonSEXP);
    Rcpp::traits::input_parameter< Function >::type numerical_moment_fallback(numerical_moment_fallbackSEXP);
    Rcpp::traits::input_parameter< Function >::type log_interval_fallback(log_interval_fallbackSEXP);
    rcpp_result_gen = Rcpp::wrap(cglbm_cpp_weighted_gaussian_em_step_raw(value, status, lower, upper, tau, omega, old_mean, old_variance, variance_group, sigma2_min, effective_weight_min, cached_complete_censoring_reason, numerical_moment_fallback, log_interval_fallback));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CGLBM_cglbm_cpp_all_cell_loglik_raw", (DL_FUNC) &_CGLBM_cglbm_cpp_all_cell_loglik_raw, 7},
    {"_CGLBM_cglbm_cpp_row_membership_scores_raw", (DL_FUNC) &_CGLBM_cglbm_cpp_row_membership_scores_raw, 3},
    {"_CGLBM_cglbm_cpp_col_membership_scores_raw", (DL_FUNC) &_CGLBM_cglbm_cpp_col_membership_scores_raw, 3},
    {"_CGLBM_cglbm_cpp_membership_objective_raw", (DL_FUNC) &_CGLBM_cglbm_cpp_membership_objective_raw, 5},
    {"_CGLBM_cglbm_cpp_weighted_gaussian_em_step_raw", (DL_FUNC) &_CGLBM_cglbm_cpp_weighted_gaussian_em_step_raw, 14},
    {NULL, NULL, 0}
};

RcppExport void R_init_CGLBM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
