# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cglbm_cpp_all_cell_loglik_raw <- function(value, status, lower, upper, block_mean, block_variance, log_interval_fallback) {
    .Call(`_CGLBM_cglbm_cpp_all_cell_loglik_raw`, value, status, lower, upper, block_mean, block_variance, log_interval_fallback)
}

cglbm_cpp_row_membership_scores_raw <- function(omega, pi, log_likelihood) {
    .Call(`_CGLBM_cglbm_cpp_row_membership_scores_raw`, omega, pi, log_likelihood)
}

cglbm_cpp_col_membership_scores_raw <- function(tau, rho, log_likelihood) {
    .Call(`_CGLBM_cglbm_cpp_col_membership_scores_raw`, tau, rho, log_likelihood)
}

cglbm_cpp_membership_objective_raw <- function(tau, omega, pi, rho, log_likelihood) {
    .Call(`_CGLBM_cglbm_cpp_membership_objective_raw`, tau, omega, pi, rho, log_likelihood)
}

cglbm_cpp_weighted_gaussian_em_step_raw <- function(value, status, lower, upper, tau, omega, old_mean, old_variance, variance_group, sigma2_min, effective_weight_min, cached_complete_censoring_reason, numerical_moment_fallback, log_interval_fallback) {
    .Call(`_CGLBM_cglbm_cpp_weighted_gaussian_em_step_raw`, value, status, lower, upper, tau, omega, old_mean, old_variance, variance_group, sigma2_min, effective_weight_min, cached_complete_censoring_reason, numerical_moment_fallback, log_interval_fallback)
}

